### PR TITLE
Fix epkg-list-matching-packages pattern argument

### PR DESCRIPTION
**Pull request by stepnem**
- fix incorrect regexp matching

- fix the doc string to match the behaviour and argument name

### CODE REVIEW

**Comment by tarsius** [comment]
Thanks for running `make texi`. Unfortunately this actually leads to more work for me because your version of Org produces results that are different from what my version of Org produces.  (I am using the `master` branch, but until recently I used `9.2.*` or the `maint` branch and I believe that lead to the same result. What version are you using?)  Your version puts `@subtitle` in the wrong place and removes the final newline character.

So please don't run `make texi`. I do all merging in Magit anyway (with the help of Forge), so running that myself is almost no work for me.

**Comment by tarsius** [comment]
And thanks for the fixes!

**Comment by stepnem** [comment]
Oh, I'm sorry! I use org master, too (currently 9.2.4-420-ga18edf),
but I don't use make, I just use org-export from the org files directly. Is that not supported? (Another thing I'm always fixing manually is that your @author line is removed during export).

**Comment by tarsius** [comment]
> I just use org-export from the org files directly. Is that not supported?

That's supposed to lead to the same result and for me it does. Well rather than investigate what's wrong when you do it, lets just have me do it.

**Comment by stepnem** [comment]
Noted, thanks.

**Pull request merged**
